[global]
log_level = 'debug'

[mode]

[mode.clients]
enabled = true
refresh = true
misbehaviour = false

[mode.connections]
enabled = false

[mode.channels]
enabled = false

[mode.packets]
enabled = true
clear_interval = 100
clear_on_start = true
tx_confirmation = false

[rest]
enabled = false
host = '127.0.0.1'
port = 3000

[telemetry]
enabled = false
host = '127.0.0.1'
port = 3001

[[chains]]
id = 'osmosis-1'
rpc_addr = 'http:///osmosis/'
websocket_addr = 'ws:///osmosis/websocket'
grpc_addr = 'http://:9001'
rpc_timeout = '30s'
account_prefix = 'osmo'
key_name = 'osmosis'
store_prefix = 'ibc'
max_gas = 15000000                                                                                          
max_msg_num = 10
gas_price = { price = 0.0001, denom = 'uosmo' }
gas_adjustment = 1
clock_drift = '15s'
trusting_period = '9days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Delegate Notional: build interchain expressway'
[chains.packet_filter]
policy = 'allow'
list = []

[[chains]]
id = 'iov-mainnet-ibc'  
rpc_addr = 'http:///starname/'
grpc_addr = 'http://:9002'
websocket_addr = 'ws:///starname/websocket'
rpc_timeout = '30s'
account_prefix = 'star'
key_name = 'starname'
store_prefix = 'ibc'       
max_gas = 2500000
max_tx_size = 180000
gas_price = { price = 0.001, denom = 'uiov' }
gas_adjustment = 1
clock_drift ='15s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Delegate Notional: build interchain expressway'
[chains.packet_filter]
policy = 'allow'
list = []

[[chains]]
id = 'regen-1'
rpc_addr= 'http:///regen/'
grpc_addr = 'http://:9003'
websocket_addr = 'ws:///regen/websocket'
rpc_timeout = '15s'   
account_prefix = 'regen'
key_name = 'regen'
store_prefix = 'ibc' 
max_tx_size = 180000
max_gas = 200000
gas_price = { price = 0.0025, denom = 'uregen' }                                                                                                                                      
gas_adjustment = 1                                                                                                                                                                    
clock_drift ='15s'                                                                                                                                                                    
trusting_period = '14days'                                                                                                                                                            
trust_threshold = { numerator = '1', denominator = '3' }                                                                                                                              
memo_prefix = 'Delegate Notional: build interchain expressway'                                                                                                                        
[chains.packet_filter]                                                                                                                                                                
policy = 'allow'                                                                                                                                                                      
list = []

[[chains]]
id = 'akashnet-2'
rpc_addr = 'http:///akash/'
websocket_addr = 'ws:///akash/websocket'
grpc_addr = 'http://:9004'
rpc_timeout = '15s'
account_prefix = 'akash'
key_name = 'akash'
store_prefix = 'ibc'
max_gas = 2000000
max_msg_num = 30
gas_price = { price = 0.001, denom = 'uakt' }
gas_adjustment = 0.1
clock_drift = '15s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Delegate Notional: build interchain expressway'
[chains.packet_filter]
policy = 'allow'
list = []

[[chains]]
id = 'cosmoshub-4'
rpc_addr = 'http:///cosmoshub/'
grpc_addr = 'http://:9005'
websocket_addr = 'ws:///cosmoshub/websocket'
rpc_timeout = '30s'
account_prefix = 'cosmos'
key_name = 'cosmos'
store_prefix = 'ibc'
max_tx_size = 180000
max_gas = 2000000
gas_price = { price = 0.00005, denom = 'uatom' }
gas_adjustment = 0.1
clock_drift = '15s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Delegate Notional: build interchain expressway'
[chains.packet_filter]
policy = 'allow'
list = []

[[chains]] 
id = 'sentinelhub-2'
rpc_addr = 'http:///sentinel/'
grpc_addr = 'http://:9006'
websocket_addr = 'ws:///akash/websocket'
account_prefix = 'sent'
rpc_timeout = '30s'
key_name = 'sentinel'
store_prefix = 'ibc'
max_gas = 2000000
max_msg_num = 30
gas_price = { price = 0.125, denom = 'udvpn' }  
gas_adjustment = 0.1
clock_drift = '15s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Delegate Notional: build interchain expressway'
[chains.packet_filter]
policy = 'allow'
list = []

[[chains]]
id = 'emoney-3'
rpc_addr = 'http:///emoney/'
grpc_addr = 'http://:9007'
websocket_addr = 'ws:///emoney/websocket'
rpc_timeout = '30s'
account_prefix = 'emoney'
key_name = 'emoney'
store_prefix = 'ibc'
max_tx_size = 180000
max_gas = 3000000
max_msg_num = 30
gas_price = { price = 0, denom = 'ungm' }
gas_adjustment = 1
clock_drift ='70s'
trusting_period = '10days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Delegate Notional: build interchain expressway'
[chains.packet_filter]
policy = 'allow'
list = []

[[chains]]
id = 'impacthub-3'
rpc_addr = 'http:///ixo/'
grpc_addr = 'http://:9008'
websocket_addr = 'ws:///ixo/websocket'
rpc_timeout = '30s'
account_prefix = 'ixo'
key_name = 'ixo'
store_prefix = 'ibc'
max_tx_size = 180000
max_gas = 3000000
max_msg_num = 30
gas_price = { price = 0, denom = 'ixo' }
gas_adjustment = 1
clock_drift ='70s'
trusting_period = '10days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Delegate Notional: build interchain expressway'
[chains.packet_filter]
policy = 'allow'
list = []

[[chains]]
id = 'juno-1'
rpc_addr = 'http:///juno/'
grpc_addr = 'http://:9009'
websocket_addr = 'ws:///juno/websocket'
rpc_timeout = '30s'
account_prefix = 'juno'
key_name = 'juno'
store_prefix = 'ibc'
max_tx_size = 1800000
max_gas = 3000000
gas_price = { price = 0.001, denom = 'ujuno' }
gas_adjustment = 0.1
clock_drift = '15s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Delegate Notional: build interchain expressway'
[chains.packet_filter]
policy = 'allow'   
list = []

[[chains]]
id = 'sifchain-1'
rpc_addr = 'http:///sifchain/'
grpc_addr = 'http://:9010'
websocket_addr = 'ws:///sifchain/websocket'
rpc_timeout = '30s'
account_prefix = 'sif' 
key_name = 'sif'
store_prefix = 'ibc'
max_gas = 1000000000000000                             
gas_price = { price = 2500, denom = 'rowan' }
gas_adjustment = 0.1
clock_drift ='15s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' } 
memo_prefix = 'Delegate Notional: build interchain expressway'
[chains.packet_filter]
policy = 'allow'    
list = []

[[chains]]
id = 'likecoin-mainnet-2'
rpc_addr = 'http:///likecoin/'
grpc_addr = 'http://:9011'
websocket_addr = 'ws:///likecoin/websocket'
rpc_timeout = '30s'
account_prefix = 'cosmos' 
key_name = 'like'
store_prefix = 'ibc'
max_gas = 1000000000000000                             
gas_price = { price = 2500, denom = 'nanolike' }
gas_adjustment = 0.1
clock_drift ='15s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' } 
memo_prefix = 'Delegate Notional: build interchain expressway'
[chains.packet_filter]
policy = 'allow'    
list = []

[[chains]]
id = 'kichain-2'    
rpc_addr = 'http:///kichain/'
grpc_addr = 'http://:9012'
websocket_addr = 'ws:///kichain/websocket'
rpc_timeout = '30s'
account_prefix = 'ki'
key_name = 'ki'
store_prefix = 'ibc'
max_gas = 2000000
max_tx_size = 180000
max_msg_num = 20
gas_price = { price = 0.026, denom = 'uxki' }
gas_adjustment = 0.1
clock_drift ='15s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Delegate Notional: build interchain expressway'
[chains.packet_filter]
policy = 'allow'
list = []

[[chains]]
id = 'bostrom'
rpc_addr = 'http:///cyber/'
grpc_addr = 'http://:9013'
websocket_addr = 'ws:///cyber/websocket'
rpc_timeout = '30s'
account_prefix = 'bostrom'
key_name = 'cyber'
store_prefix = 'ibc'
max_tx_size = 180000
max_gas = 3000000
max_msg_num = 30
gas_price = { price = 0, denom = 'boot' }
gas_adjustment = 1
clock_drift ='70s'
trusting_period = '7days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Delegate Notional: build interchain expressway'
[chains.packet_filter]
policy = 'allow'
list = []

[[chains]]
id = 'cheqd-mainnet-1'    
rpc_addr = 'http:///cheqd/'
grpc_addr = 'http://:9014'
websocket_addr = 'ws:///cheqd/websocket'
rpc_timeout = '30s'
account_prefix = 'cheq'
key_name = 'cheq'
store_prefix = 'ibc'
max_gas = 2000000
max_tx_size = 180000
max_msg_num = 20
gas_price = { price = 269, denom = 'ncheq' }
gas_adjustment = 0.1
clock_drift ='15s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Delegate Notional: build interchain expressway'
[chains.packet_filter]
policy = 'allow'
list = []

[[chains]]                                                                                                                                                                            
id='stargaze-1'                                                                                                                                                                     
rpc_addr='http:///stargaze/'                                                                                                                                          
grpc_addr = 'http://:9015'
websocket_addr = 'ws:///stargaze/websocket'
rpc_timeout = '10s'
account_prefix = 'stars'
key_name = 'stars'
store_prefix = 'ibc'
max_gas = 2000000   
gas_price = { price = 0.025, denom = 'ustars' }
gas_adjustment = 0.1
clock_drift = '300s' 
trusting_period = '10days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Delegate Notional: build interchain expressway'
[chains.packet_filter]
policy = 'allow'
list = []

[[chains]]
id = 'laozi-mainnet'
rpc_addr = 'http:///bandchain/'
grpc_addr = 'http://:9016'
websocket_addr = 'ws:///bandchain/websocket'
rpc_timeout = '15s'
account_prefix = 'band'
key_name = 'band'
store_prefix = 'ibc'
max_gas = 2000000
gas_price = { price = 0.0001, denom = 'uband' }
gas_adjustment = 1
clock_drift = '15s'
trusting_period = '7days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Delegate Notional: build interchain expressway'
[chains.packet_filter]
policy = 'allow'
list = []

[[chains]]
id = 'chihuahua-1' 
rpc_addr = 'http:///chihuahua/'
grpc_addr = 'http://:9017'
websocket_addr = 'ws:///chihuahua/websocket'
rpc_timeout = '15s'
account_prefix = 'chihuahua'
key_name = 'chihuahua'
store_prefix = 'ibc'
max_tx_size = 450000      
max_gas = 1000000
max_msg_num = 30
gas_price = { price = 0.1, denom = 'uhuahua' }
gas_adjustment = 1
clock_drift ='15s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Delegate Notional: build interchain expressway'
[chains.packet_filter]
policy = 'allow' 
list = []

[[chains]]
id = 'kava-9'
rpc_addr = 'http:///kava/'
grpc_addr = 'http://:9018'
websocket_addr = 'ws:///kava/websocket'
rpc_timeout = '30s'
account_prefix = 'kava'
key_name = 'kava'
store_prefix = 'ibc'
max_tx_size = 180000
max_gas = 2000000
gas_price = { price = 0, denom = 'ukava' }
gas_adjustment = 0.1
clock_drift = '15s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Delegate Notional: build interchain expressway'
[chains.packet_filter]
policy = 'allow'
list = []


[[chains]]
id = 'bitcanna-1'
rpc_addr = 'http:///bitcanna/'                    
grpc_addr = 'http://:9019'
websocket_addr = 'ws:///bitcanna/websocket'
rpc_timeout = '15s'
account_prefix = 'bcna'
key_name = 'bcna'
store_prefix = 'ibc'
max_gas = 2000000  
gas_price = { price = 0.001, denom = 'ubcna' }
gas_adjustment = 1    
clock_drift ='15s'  
trusting_period = '7days' 
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Delegate Notional: build interchain expressway'
[chains.packet_filter]
policy = 'allow'  
list = []

[[chains]]
id = 'darchub'
rpc_addr = 'http:///konstellation/'
grpc_addr = 'http://:9020'
websocket_addr = 'ws:///konstellation/websocket'
rpc_timeout = '30s'
account_prefix = 'darc'
key_name = 'darc'
max_tx_size = 650000
store_prefix = 'ibc'
max_gas = 1000000 
gas_price = { price = 0.01, denom = 'udarc' }
gas_adjustment = 1
clock_drift ='10s'
trusting_period = '14days'
memo_prefix = 'Delegate Notional: build interchain expressway'
trust_threshold = { numerator = '1', denominator = '3' }
[chains.packet_filter]
policy = 'allow'
list = []

[[chains]]
id = 'omniflixhub-1'
rpc_addr = 'http:///omniflixhub/'
grpc_addr = 'http://:9021'
websocket_addr = 'ws:///omniflixhub/websocket'
rpc_timeout = '15s'
account_prefix = 'omniflix'
key_name = 'omniflix'
max_tx_size = 180000
store_prefix = 'ibc'
max_gas = 2000000
gas_price = { price = 0.005, denom = 'uflix' }
gas_adjustment = 0.1
clock_drift = '15s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Delegate Notional: build interchain expressway'
[chains.packet_filter]
policy = 'allow'
list = []

[[chains]]
id = 'columbus-5'
rpc_addr = 'http:///terra/'
grpc_addr = 'http://:9022'
websocket_addr = 'ws:///terra/websocket'
rpc_timeout = '30s'
account_prefix = 'terra'
key_name = 'terra'
max_tx_size = 650000
store_prefix = 'ibc'
max_gas = 700000  
gas_price = { price = 25, denom = 'ukrw' }
gas_adjustment = 0.1
clock_drift ='5s'
trusting_period = '14days'
memo_prefix = 'Delegate Notional: build interchain expressway'
trust_threshold = { numerator = '1', denominator = '3' }
[chains.packet_filter]
policy = 'allow'
list = []

[[chains]]
id = 'vidulum-1'
rpc_addr = 'http:///vidulum/'
grpc_addr = 'http://:9023'
websocket_addr = 'ws:///vidulum/websocket'
rpc_timeout = '30s'
account_prefix = 'vdl'
key_name = 'vidulum'
store_prefix = 'ibc'
max_tx_size = 180000
max_gas = 3000000
max_msg_num = 30
gas_price = { price = 0, denom = 'uvdl' }
gas_adjustment = 1
clock_drift ='70s'
trusting_period = '10days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Delegate Notional: build interchain expressway'
[chains.packet_filter]
policy = 'allow'
list = []

[[chains]]
id = 'pio-mainnet-1'
rpc_addr = 'http:///provenance/'
grpc_addr = 'http://:9024'
websocket_addr = 'ws:///provenance/websocket'
rpc_timeout = '30s'
account_prefix = 'pb'
key_name = 'provenance'
store_prefix = 'ibc'
max_tx_size = 180000
max_gas = 3000000
max_msg_num = 30
gas_price = { price = 0, denom = 'uhash' }
gas_adjustment = 1
clock_drift ='70s'
trusting_period = '10days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Delegate Notional: build interchain expressway'
[chains.packet_filter]
policy = 'allow'
list = []

[[chains]]
id = 'dig-1'
rpc_addr = 'http:///dig/'
grpc_addr = 'http://:9025'
websocket_addr = 'ws:///dig/websocket'
rpc_timeout = '30s'
account_prefix = 'dig'
key_name = 'dig'
store_prefix = 'ibc'
max_gas = 7000000
max_tx_size = 1500000
gas_price = { price = 0.001, denom = 'udig' }
gas_adjustment = 0.1
clock_drift ='5s'
trusting_period = '7days'
memo_prefix = 'Delegate Notional: build interchain expressway'
trust_threshold = { numerator = '1', denominator = '3' }
[chains.packet_filter]
policy = 'allow'
list = []


[[chains]]
id = 'gravity-bridge-3'
rpc_addr = 'http:///gravitybridge/'
grpc_addr = 'http://:9026'
websocket_addr = 'ws:///gravitybridge/websocket'
rpc_timeout = '10s'
account_prefix = 'gravity'
key_name = 'gravity'
address_type = { derivation = 'cosmos' }
store_prefix = 'ibc'
default_gas = 1600000
max_gas = 5000000
gas_price = { price = 0.0261, denom = 'ugraviton' }
gas_adjustment = 0.2
max_msg_num = 30
max_tx_size = 1800000
clock_drift = '15s'
max_block_time = '10s'
trusting_period = '14days'
memo_prefix = 'Delegate Notional: build interchain expressway'
trust_threshold = { numerator = '1', denominator = '3' }
[chains.packet_filter]
policy = 'allow'
list = []








            
