[global]
log_level = 'debug'

[mode]

[mode.clients]
enabled = false
refresh = false
misbehaviour = false

[mode.connections]
enabled = false

[mode.channels]
enabled = false

[mode.packets]
enabled = true
clear_interval = 200
clear_on_start = true
tx_confirmation = false

[rest]
enabled = false
host = '127.0.0.1'
port = 3000

[telemetry]
enabled = false
host = '127.0.0.1'
port = 3001

[[chains]]
id = 'omniflixhub-1'
rpc_addr = 'http://127.0.0.1:2301'
grpc_addr = 'http://127.0.0.1:2302'
websocket_addr = 'ws://localhost:2301/websocket'
rpc_timeout = '15s'
account_prefix = 'omniflix'
key_name = 'omniflix'
max_tx_size = 180000
store_prefix = 'ibc'
max_gas = 2000000
fee_granter = 'omniflix1p3736gw3mll4m5k5r80w3jvc9lynvz4t5zkvrw'
gas_price = { price = 0.0035, denom = 'uflix' }
gas_adjustment = 0.1
clock_drift = '15s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Relayed by Notional!'
[chains.packet_filter]
policy = 'allow'
list = [ 
['transfer', 'channel-0'], ['transfer', 'channel-1'], 
['transfer', 'channel-2'], ['transfer', 'channel-3'], 
['transfer', 'channel-4'], ['transfer', 'channel-5'], 
['transfer', 'channel-6'], ['transfer', 'channel-7'], 
['transfer', 'channel-8'], ['transfer', 'channel-9'],
['transfer', 'channel-10'], ['transfer', 'channel-11'],
['transfer', 'channel-12'], ['transfer', 'channel-13'],
['transfer', 'channel-14'], ['transfer', 'channel-15'],
['transfer', 'channel-16'], ['transfer', 'channel-17'],
['transfer', 'channel-18'], ['transfer', 'channel-19'],
]

[[chains]]
id = 'sifchain-1'
rpc_addr = 'http://127.0.0.1:2111'
grpc_addr = 'http://127.0.0.1:2112'
websocket_addr = 'ws://127.0.0.1:2111/websocket'
rpc_timeout = '30s'
account_prefix = 'sif'
key_name = 'sif'
store_prefix = 'ibc'
max_gas = 1000000000000000
gas_price = { price = 20000, denom = 'rowan' }
gas_adjustment = 0.1
clock_drift ='15s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Relayed by Notional!'
[chains.packet_filter]
policy = 'allow'
list = [
['transfer', 'channel-44'], ['transfer', 'channel-0'],
['transfer', 'channel-17'], ['transfer', 'channel-14'],
['transfer', 'channel-2'], ['transfer', 'channel-41'],
['transfer', 'channel-38'], ['transfer', 'channel-40'],
['transfer', 'channel-35'], ['transfer', 'channel-9'],
['transfer', 'channel-7'], ['transfer', 'channel-49']
]

[[chains]]
id = 'cosmoshub-4'
rpc_addr = 'http://127.0.0.1:2011'
grpc_addr = 'http://127.0.0.1:2012'
websocket_addr = 'ws://127.0.0.1:2011/websocket'
rpc_timeout = '15s'
account_prefix = 'cosmos'
key_name = 'cosmos'
store_prefix = 'ibc'
max_gas = 2000000
max_tx_size = 180000
max_msg_num = 20
gas_price = { price = 0.000025, denom = 'uatom' }
gas_adjustment = 0.1
clock_drift ='15s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Relayed by Notional!'
[chains.packet_filter]
policy = 'allow'
list = [ 
['transfer', 'channel-290'], ['transfer', 'channel-192']
]

[[chains]]
id = 'osmosis-1'
rpc_addr = 'http://127.0.0.1:2001'
grpc_addr = 'http://127.0.0.1:2002'
websocket_addr = 'ws://localhost:2001/websocket'
rpc_timeout = '20s'
account_prefix = 'osmo'
key_name = 'osmosis'
max_tx_size = 180000
store_prefix = 'ibc'
max_gas = 2000000
fee_granter = ''
gas_price = { price = 0.00025, denom = 'uosmo' }
gas_adjustment = 0.1
clock_drift = '15s'
trusting_period = '10days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Relayed by Notional!'
[chains.packet_filter]
policy = 'allow'
list = [
['transfer', 'channel-199'], ['transfer', 'channel-47']
]

[[chains]]
id = 'juno-1'
rpc_addr = 'http://127.0.0.1:2071'
grpc_addr = 'http://127.0.0.1:2072'
websocket_addr = 'ws://127.0.0.1:2071/websocket'
rpc_timeout = '30s'
account_prefix = 'juno'
key_name = 'juno'
store_prefix = 'ibc'
max_tx_size = 180000
max_gas = 2000000
gas_price = { price = 0.00025, denom = 'ujuno' }
gas_adjustment = 0.1
clock_drift = '15s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Relayed by Notional!'
[chains.packet_filter]
policy = 'allow'
list = [
['transfer', 'channel-63'], ['transfer', 'channel-5']
]

[[chains]]
id = 'gravity-bridge-3'
rpc_addr = 'http://127.0.0.1:2311'
grpc_addr = 'http://127.0.0.1:2312'
websocket_addr = 'ws://127.0.0.1:2311/websocket'
rpc_timeout = '10s'
account_prefix = 'gravity'
key_name = 'gravity'
address_type = { derivation = 'cosmos' }
store_prefix = 'ibc'
default_gas = 1600000
max_gas = 5000000
gas_price = { price = 0.0261, denom = 'ugraviton' }
gas_adjustment = 0.2
max_msg_num = 30
max_tx_size = 1800000
clock_drift = '15s'
max_block_time = '10s'
trusting_period = '14days'
memo_prefix = 'Relayed by Notional!'
trust_threshold = { numerator = '1', denominator = '3' }
[chains.packet_filter]
policy = 'allow'
list = [
['transfer', 'channel-35'],
]

[[chains]]
id = 'columbus-5'
rpc_addr = 'http://127.0.0.1:2161'
grpc_addr = 'http://127.0.0.1:2162'
websocket_addr = 'ws://127.0.0.1:2161/websocket'
rpc_timeout = '30s'
account_prefix = 'terra'
key_name = 'terra'
max_tx_size = 650000
store_prefix = 'ibc'
max_gas = 700000
gas_price = { price = 170, denom = 'ukrw' }
gas_adjustment = 0.1
clock_drift ='5s'
trusting_period = '14days'
memo_prefix = 'Relayed by Notional!'
trust_threshold = { numerator = '1', denominator = '3' }
[chains.packet_filter]
policy = 'allow'
list = [
['transfer', 'channel-27'],
]

[[chains]]
id = 'chihuahua-1'
rpc_addr = 'http://127.0.0.1:2241'
grpc_addr = 'http://127.0.0.1:2242'
websocket_addr = 'ws://127.0.0.1:2241/websocket'
rpc_timeout = '15s'
account_prefix = 'chihuahua'
key_name = 'chihuahua'
store_prefix = 'ibc'
max_tx_size = 450000
max_gas = 1000000
max_msg_num = 30
gas_price = { price = 0.025, denom = 'uhuahua' }
gas_adjustment = 1
clock_drift ='15s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Relayed by Notional!'
[chains.packet_filter]
policy = 'allow'
list = [
['transfer', 'channel-17'], ['transfer', 'channel-8']
]

[[chains]]
id = 'akashnet-2'
rpc_addr = 'http://127.0.0.1:2021'
grpc_addr = 'http://127.0.0.1:2022'
websocket_addr = 'ws://127.0.0.1:2021/websocket'
rpc_timeout = '15s'
account_prefix = 'akash'
key_name = 'akash'
store_prefix = 'ibc'
max_gas = 2000000
max_msg_num = 30
gas_price = { price = 0.001, denom = 'uakt' }
gas_adjustment = 0.1
clock_drift = '10s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Relayed by Notional!'
[chains.packet_filter]
policy = 'allow'
list = [
['transfer', 'channel-39'], ['transfer', 'channel-24']
]

[[chains]]
id = 'stargaze-1'
rpc_addr = 'http://127.0.0.1:2191'
grpc_addr = 'http://127.0.0.1:2192'
websocket_addr = 'ws://127.0.0.1:2191/websocket'
rpc_timeout = '15s'
account_prefix = 'stars'
key_name = 'stargaze'
store_prefix = 'ibc'
max_gas = 2000000
gas_price = { price = 1.0, denom = 'stars' }
gas_adjustment = 1.0
clock_drift = '10s'
trusting_period = '7days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Relayed by Notional!'
[chains.packet_filter]
policy = 'allow'
list = [
['transfer', 'channel-36'], ['transfer', 'channel-12']
]

[[chains]]
id = 'sentinelhub-2'
rpc_addr = 'http://127.0.0.1:2031'
grpc_addr = 'http://127.0.0.1:2032'
websocket_addr = 'ws://127.0.0.1:2031/websocket'
account_prefix = 'sent'
rpc_timeout = '30s'
key_name = 'sentinel'
store_prefix = 'ibc'
max_gas = 2000000
max_msg_num = 30
gas_price = { price = 0.011, denom = 'udvpn' }
gas_adjustment = 0.1
clock_drift = '15s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Relayed by Notional!'
[chains.packet_filter]
policy = 'allow'
list = [
['transfer', 'channel-53'], ['transfer', 'channel-36']
]

[[chains]]
id = 'crypto-org-chain-mainnet-1'
rpc_addr = 'http://127.0.0.1:2041'
grpc_addr = 'http://127.0.0.1:2042'
websocket_addr = 'ws://127.0.0.1:2041/websocket'
rpc_timeout = '10s'
account_prefix = 'cro'
key_name = 'crypto'
store_prefix = 'ibc'
max_gas = 2000000
max_tx_size = 450000
gas_price = { price = 0.06, denom = 'basecro' }
gas_adjustment = 0.1
clock_drift ='15s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Relayed by Notional!'
[chains.packet_filter]
policy = 'allow'
list = [
['transfer', 'channel-54'], ['transfer', 'channel-33']
]
