[global]
log_level = 'debug'

[mode]

[mode.clients]
enabled = false
refresh = true
misbehaviour = true

[mode.connections]
enabled = false

[mode.channels]
enabled = false

[mode.packets]
enabled = true
clear_interval = 25
clear_on_start = true
tx_confirmation = false

[rest]
enabled = false
host = '127.0.0.1'
port = 3000

[telemetry]
enabled = false
host = '127.0.0.1'
port = 3001

[[chains]]
id = 'osmosis-1'
rpc_addr = 'http:///osmosis/'
websocket_addr = 'ws:///osmosis/websocket'
grpc_addr = 'http://:9001'
rpc_timeout = '30s'
account_prefix = 'osmo'
key_name = 'osmosis'
store_prefix = 'ibc'
max_gas = 11990000                                                                                          
gas_price = { price = 0, denom = 'uosmo' }
gas_adjustment = 1
clock_drift = '7200s'
trusting_period = '1days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Relayed by Notional!'
[chains.packet_filter]
policy = 'allow'
list = [
['trnsfer', 'channel-0']
]

[[chains]]
id = 'cosmoshub-4'
rpc_addr = 'http:///cosmoshub/'
grpc_addr = 'http://:9005'
websocket_addr = 'ws:///cosmoshub/websocket'
rpc_timeout = '30s'
account_prefix = 'cosmos'
key_name = 'cosmos'
store_prefix = 'ibc'
max_tx_size = 119900
max_gas = 11990000
gas_price = { price = 0, denom = 'uatom' }
gas_adjustment = 0.1
clock_drift = '7200s'
trusting_period = '1days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Relayed by Notional!'
[chains.packet_filter]
policy = 'allow'
list = [
['transfer', 'channel-141']
]
