name: sos

on: [push, pull_request, workflow_dispatch]

jobs:
  arm64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes --credential yes

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Build
        run: bash build.sh

      - name: Compress
        run: xz -T $(nproc) images/sos.img

      - name: Upload image
        uses: actions/upload-artifact@v2
        with:
          name: sos
          path: images/sos.img.xz
  amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Build
        run: bash build.sh

      - name: Compress
        run: xz -T $(nproc) images/sos.img

      - name: Upload image
        uses: actions/upload-artifact@v2
        with:
          name: sos
          path: images/sos.img.xz

